

-- get_optimization_returns.sql (FINAL VERSION)


USE DATABASE FAMA_FRENCH;
USE SCHEMA PROCESSED_COMPUSTAT_DATA;

CREATE OR REPLACE TABLE PROCESSED_COMPUSTAT_DATA.OPTIMIZATION_PORTFOLIO_DAILY_PRICES AS
WITH
    -- This CTE is no longer needed as we pass the tickers directly
    -- ALLOWED_TICKERS_CTE AS (...)
    
    TARGET_SECURITY_IDENTIFIERS AS (
        SELECT
            s.GVKEY, s.IID, sid.ITEMVALUE AS RAW_TICKER, c.CONM AS COMPANY_NAME,
            UPPER(sid.ITEMVALUE) AS TICKER_UPPERCASE,
            s.EXCHG, s.TPCI,
            ROW_NUMBER() OVER (
                PARTITION BY UPPER(sid.ITEMVALUE)
                ORDER BY CASE s.TPCI WHEN '0' THEN 1 ELSE 2 END ASC,
                         CASE s.EXCHG WHEN '11' THEN 1 WHEN '14' THEN 2 WHEN '13' THEN 3 WHEN '12' THEN 4 WHEN '19' THEN 5 ELSE 6 END ASC,
                         s.IID ASC
            ) as rn
        FROM spglobalxpresscloud_spglobalxpresscloud_aws_us_east_1_xf_l32partners.xpressfeed.SEC_IDCURRENT sid
        JOIN spglobalxpresscloud_spglobalxpresscloud_aws_us_east_1_xf_l32partners.xpressfeed.SECURITY s
            ON sid.GVKEY = s.GVKEY AND sid.IID = s.IID
        JOIN spglobalxpresscloud_spglobalxpresscloud_aws_us_east_1_xf_l32partners.xpressfeed.COMPANY c
            ON s.GVKEY = c.GVKEY
        WHERE
            sid.ITEM = 'TIC'
            -- This is the key change. We use the substituted variable directly in an IN clause.
            AND UPPER(TRIM(sid.ITEMVALUE)) IN (&{TICKER_LIST_VAR})
            AND s.SECSTAT = 'A'
    ),
    PRIMARY_TARGET_IDENTIFIERS AS (
        SELECT GVKEY, IID, RAW_TICKER AS TICKER, COMPANY_NAME FROM TARGET_SECURITY_IDENTIFIERS WHERE rn = 1
    ),
    -- The rest of the query remains the same...
    TARGET_DAILY_TRADING_RAW AS (
        SELECT 
            pid.TICKER, pid.COMPANY_NAME, d.GVKEY, d.IID, d.DATADATE, d.PRCCD AS PRICE_CLOSE_UNADJ, 
            COALESCE(d.AJEXDI, 1.0) AS ADJUSTMENT_FACTOR_DAILY 
        FROM spglobalxpresscloud_spglobalxpresscloud_aws_us_east_1_xf_l32partners.xpressfeed.SEC_DPRC d 
        JOIN PRIMARY_TARGET_IDENTIFIERS pid ON d.IID = pid.IID AND d.GVKEY = pid.GVKEY 
        WHERE d.DATADATE BETWEEN DATEADD(year, -7, CURRENT_DATE()) AND DATEADD(day, -1, CURRENT_DATE()) 
          AND d.PRCCD IS NOT NULL AND d.PRCCD > 0 AND DAYOFWEEKISO(d.DATADATE) BETWEEN 1 AND 5
    ),
    ADJUSTED_DAILY_PRICES AS (
        SELECT 
            TICKER, COMPANY_NAME, GVKEY, IID, DATADATE, 
            (PRICE_CLOSE_UNADJ / ADJUSTMENT_FACTOR_DAILY) AS ADJUSTED_PRICE_CLOSE 
        FROM TARGET_DAILY_TRADING_RAW
    )
SELECT TICKER, COMPANY_NAME, DATADATE, ADJUSTED_PRICE_CLOSE, GVKEY, IID
FROM ADJUSTED_DAILY_PRICES ORDER BY TICKER, DATADATE;

CREATE OR REPLACE TABLE PROCESSED_COMPUSTAT_DATA.OPTIMIZATION_PORTFOLIO_MONTHLY_RETURNS AS
WITH 
    DAILY_PRICES_FILTERED AS (
        SELECT * FROM PROCESSED_COMPUSTAT_DATA.OPTIMIZATION_PORTFOLIO_DAILY_PRICES
    ),
    MONTHLY_END_PRICES AS (
        SELECT 
            TICKER, LAST_DAY(DATADATE, 'MONTH') AS MONTH_END_DATE, GVKEY, IID,
            FIRST_VALUE(ADJUSTED_PRICE_CLOSE) OVER (PARTITION BY TICKER, LAST_DAY(DATADATE, 'MONTH') ORDER BY DATADATE DESC) AS LAST_ADJUSTED_PRICE_OF_MONTH 
        FROM DAILY_PRICES_FILTERED
    ),
    DISTINCT_MONTHLY_END_PRICES AS (
        SELECT DISTINCT TICKER, MONTH_END_DATE, GVKEY, IID, LAST_ADJUSTED_PRICE_OF_MONTH FROM MONTHLY_END_PRICES
    )
SELECT 
    TICKER, MONTH_END_DATE, GVKEY, IID, LAST_ADJUSTED_PRICE_OF_MONTH, 
    (LAST_ADJUSTED_PRICE_OF_MONTH / LAG(LAST_ADJUSTED_PRICE_OF_MONTH, 1) OVER (PARTITION BY TICKER ORDER BY MONTH_END_DATE)) - 1 AS MONTHLY_RETURN
FROM DISTINCT_MONTHLY_END_PRICES 
QUALIFY MONTHLY_RETURN IS NOT NULL 
ORDER BY TICKER, MONTH_END_DATE;